### ISSUE TITLE
enable numeric precision

### ISSUE THREAD

**Issue by sbowman-mitre** [shaovoon/minicsv#11]
Hi, I have been using this library for a few years; thank you for creating it. This comment is when using v1.8.1. 

One struggle I've had is in the ability to control numeric precision. My uses are nearly all focused on writing number values to CSV and sometimes I need control over the precision of the numeric values. While one can set it this way:

```
mini::csv::ofstream os(filename.c_str());
os.set_delimiter(',', ",");
os.get_ofstream().precision(15);  // <-- this compiles, but does not control precision
auto data_inserter = [&os](const DataToWrite &data_row) {
  os << Units::SecondsTime(data_row.time).value();
  os << NEWLINE;
  os.flush();
};
std::for_each(m_data_to_write.cbegin(), m_data_to_write.cend(), data_inserter);
os.close();
```

However, I have found that the call to `precision` does not properly control the output. Any idea why? Or is there a better way to do this?

**Comment by shaovoon** [comment]
Thanks for your feedback.

During this weekend, I'll modify the code so that your precision() works on get_ofstream().

**Comment by shaovoon** [comment]
I have added 3 methods to the ostream_base.

```Cpp
// Set float precision
void set_precision(int precision_);

// Get float precision
int get_precision();

// Reset float precision to zero
void reset_precision();
```

This is the way to call it,

```Cpp
mini::csv::ofstream os(filename.c_str());
os.set_delimiter(',', ",");
os.set_precision(15);
```

This is in version v1.8.7 and master. The unit tests are passing. Let me know if it breaks anything.

**Comment by sbowman-mitre** [comment]
I'll pull it in & start using it -- thank you so much!
