### ISSUE TITLE
Support `fixed` and `scientific` float formats

### ISSUE THREAD

**Issue by sbowman-mitre** [shaovoon/minicsv#12]
Maybe I'm missing it, but I don't think it's possible in v1.8.7 to format float/decimal data when writing it. I'd like to be able to decide in my code how a decimal value is represented when it is written, similar to:

https://en.cppreference.com/w/cpp/io/manip/fixed

@shaovoon  Do you recommend a specific way of doing this when using `minicsv` to write the data?

**Comment by sbowman-mitre** [comment]
In looking through the code more, I'm surprised by the fact that I'm getting scientific notation for very small numbers. My write operation should be hitting this line:
https://github.com/shaovoon/minicsv/blob/c040e27891c91c1826a7f4e2efe4f2b4f0910af5/MiniCSV/minicsv.h#L1170-L1175

which clearly calls `std::fixed`. But somehow I'm still getting values in my csv file that contain scientific notation: 
```
...,-1.56188e-05,...
```

**Comment by shaovoon** [comment]
You can modify the `test_precision()` or `test_file_precision()` function to test. I put this `test_precision()` here for your convenience. You did not call `set_precision()` on the output stream. I apologize for not being clear on this.

```Cpp
bool test_precision(const std::string& name, bool enable_quote, char delimiter, const std::string& escape)
{
	csv::ostringstream os;
	os.set_delimiter(delimiter, escape);
	os.enable_surround_quote_on_str(enable_quote, '\"');

	//double pi = 3.14159265359;
	double pi = -1.56188e-05;
	for (int i = 1; i < 12; ++i)
	{
		os.set_precision(i); // <=========== You need to call set_precision() to use std::fixed!
		os << name << pi << name << NEWLINE;
		std::cout << std::fixed << std::showpoint << std::setprecision(i) 
                              << "Source Number: " << pi << std::endl;
	}

	csv::istringstream is(os.get_text().c_str());
	is.set_delimiter(delimiter, escape);
	is.enable_trim_quote_on_str(enable_quote, '\"');

	std::string dest_name = "";
	double dest_pi = 0.0;
	std::string dest_name2 = "";

	int cnt = 0;
	while (is.read_line())
	{
		try
		{
			std::cout << is.get_rest_of_line() << std::endl;
			//is >> dest_name >> dest_pi >> dest_name2;

			//std::cout << std::fixed << std::showpoint << std::setprecision(cnt + 1) 
                       //                << "Number: " << dest_pi << std::endl;

			dest_pi = 0.0;

			++cnt;
		}
		catch (std::runtime_error& e)
		{
			std::cerr << __FUNCTION__ << e.what() << std::endl;
		}
	}
	MYASSERT(__FUNCTION__, cnt, 11);
	return true;
}
```

This is the output from Visual C++ 2022. What compiler did you use?

```
Source Number: -0.0
Source Number: -0.00
Source Number: -0.000
Source Number: -0.0000
Source Number: -0.00002
Source Number: -0.000016
Source Number: -0.0000156
Source Number: -0.00001562
Source Number: -0.000015619
Source Number: -0.0000156188
Source Number: -0.00001561880
Fruits World,-0.0,Fruits World
Fruits World,-0.00,Fruits World
Fruits World,-0.000,Fruits World
Fruits World,-0.0000,Fruits World
Fruits World,-0.00002,Fruits World
Fruits World,-0.000016,Fruits World
Fruits World,-0.0000156,Fruits World
Fruits World,-0.00001562,Fruits World
Fruits World,-0.000015619,Fruits World
Fruits World,-0.0000156188,Fruits World
Fruits World,-0.00001561880,Fruits World
```

This is the file output from test_file_precision().
[test_file_precision.txt](https://github.com/shaovoon/minicsv/files/11641690/test_file_precision.txt)

**Comment by sbowman-mitre** [comment]
Ah, yes, you are correct. I was working with some of my older code that did not take #11 into account. That's my mistake. Sorry!
